= WDL-Kit Changelog
:uri-repo: https://github.com/susom/wdl-kit
:uri-jira: https://stanfordmed.atlassian.net/browse
:icons: font
:star: icon:star[role=red]
ifndef::icons[]
:star: &#9733;
endif::[]

== Release 2024-11-21 (v1.9.7)
* ({uri-jira}/PEDS-1323[PEDS-1323]) - Update WDL-Kit to backup large size table

== Release 2024-11-21 (v1.9.6)
* ({uri-jira}/STAR-9376[STAR-9376]) - Add properties filtering for Blob 

== Release 2024-05-07 (v1.9.5)
* ({uri-jira}/STAR-8247[STAR-8247]) - Add ACL and labels to confidential dataset for OMOP and Pedsnet
* ({uri-jira}/STAR-8336[STAR-8336]) - Bug fix: Dockerfile for wdl-kit name
* ({uri-jira}/STAR-8342[STAR-8342]) - Filter extra attributes on dataset access entry for ACL update

== Release 2024-03-26 (v1.9.1)
* dependabot[bot] - Bump requests from 2.28.1 to 2.31.0
Bumps [requests](https://github.com/psf/requests) from 2.28.1 to 2.31.0.
- [Release notes](https://github.com/psf/requests/releases)
- [Changelog](https://github.com/psf/requests/blob/main/HISTORY.md)
- [Commits](psf/requests@v2.28.1...v2.31.0)
* dependabot[bot] - Bump aiohttp from 3.8.3 to 3.8.5
Bumps [aiohttp](https://github.com/aio-libs/aiohttp) from 3.8.3 to 3.8.5.
- [Release notes](https://github.com/aio-libs/aiohttp/releases)
- [Changelog](https://github.com/aio-libs/aiohttp/blob/v3.8.5/CHANGES.rst)
- [Commits](aio-libs/aiohttp@v3.8.3...v3.8.5)
* dependabot[bot] - Bump cryptography from 39.0.2 to 41.0.3
Bumps [cryptography](https://github.com/pyca/cryptography) from 39.0.2 to 41.0.3.
- [Changelog](https://github.com/pyca/cryptography/blob/main/CHANGELOG.rst)
- [Commits](pyca/cryptography@39.0.2...41.0.3)

== Release 2024-03-11 (v1.8.0)
* ({uri-jira}/PEDS-1178[PEDS-1178]) - Fix Postgres CSV import failure issue for Pedsnet data validation
* Bumped version of wdl-kit to v1.8.0

== Release 2024-02-26 (v1.7.1)
* Joe made some changes to fix build issue
* ({uri-jira}/STAR-7988[STAR-7988]) - Add missing attributes for Dataset in Struct.wdl
* ({uri-jira}/STAR-7714[STAR-7714]) - Add new function update_acl in wdl-kit and also add acl in create_dataset as optional. wdl + python

== Release 2024-01-31 (v1.7.0)
* ({uri-jira}/STAR-7609[STAR-7609]) - Change WDL-kit so that it does not crash when Google introduces new fields to API resources
* ({uri-jira}/STARR-7444[STARR-7444]) - Added storage biling, physical by default

== Release 2023-10-30 (v1.6.1) 👻
* ({uri-jira}/PEDS-1051[PEDS-1051]) - Include missing sslMode field to IpConfiguration

== Release 2023-03-02 (v1.5.0)
* ({uri-jira}/WDL-9[WDL-9]) - Add GCS functionality for file upload
* ({uri-jira}/WDL-15[WDL-15]) - Change the output of the upload object to a struct Blob instead of string for file upload functionality
* ({uri-jira}/WDL-22[WDL-22]) - Unplanned: Add CSV File column/row modification function and dockerize it for Pedsnet Postgres Validation
* ({uri-jira}/WDL-25[WDL-25]) - Add maxTimeTravelHours and isCaseInsensitive to Dataset struct
* ({uri-jira}/PEDS-697[PEDS-697]) - Integrate Backup Utility (in WDL-kit) to Post-DEID workflow 

== Release 2022-11-16 (v1.4.0)
* ({uri-jira}/WDL-7[WDL-7]) - Add more functionality to Cloud-SQL support in WDL-kit
* ({uri-jira}/WDL-8[WDL-8]) - Correct the reference to project_id in cloudsql.py instance creation
* ({uri-jira}/WDL-9[WDL-9]) - Add GCS functionality to WDL-kit for file upload
* ({uri-jira}/WDL-10[WDL-10]) - Add Cloud SQL Import CSV file function to WDL-Kit
* ({uri-jira}/WDL-12[WDL-12]) - Add IAM user option when creating an instance
* ({uri-jira}/WDL-13[WDL-13]) - Bump cloud SDK to latest version (includes Python 3.9.2)
* ({uri-jira}/WDL-14[WDL-14]) - Add CSV/JSON/HTML output to CloudSQL query command
* ({uri-jira}/WDL-15[WDL-15]) - Change the output of the upload object to a struct Blob instead of string on WDL-kit for file upload functionality
* ({uri-jira}/WDL-16[WDL-16]) - Optional flag for 'bucket' with Instance creation/insertion

== Release 2022-10-06 (v1.3.0)
* ({uri-jira}/WDL-5[WDL-5]) - Support for GCP Cloud SQL instance creation
* ({uri-jira}/STAR-6039[STAR-6039]) - Add options for delimiter and header in output CSV for BigQuery

== Release 2022-08-11 (v1.2.1)
* ({uri-jira}/WDL-3[WDL-3]) - WDL-kit integration test workflow

== Release 2022-08-11 (v1.2.0)
* ({uri-jira}/PEDS-329[PEDS-329]) - Prepare WDL-Kit for publishing to PyPi

== Release 2022-08-02 (v1.1.0)
* ({uri-jira}/STAR-5883[STAR-5883]) - BigQuery tool now defaults to Priority.BATCH, to avoid > 100 interactive job quota cancellations
