steps:
  # Docker Build
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "${_ARTIFACT_REGISTRY_REPO}/wdl-kit:1.0.0${_SUFFIX}", "-t", "${_ARTIFACT_REGISTRY_REPO}/wdl-kit:${SHORT_SHA}", "-t", "${_ARTIFACT_REGISTRY_REPO}/wdl-kit:${BUILD_ID}", "."]

  # Docker push to Google Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "-a", "${_ARTIFACT_REGISTRY_REPO}/wdl-kit"]

logsBucket: "gs://cloud-build-dev.starr-data.us"
