steps:
  - name: docker
    entrypoint: "/bin/bash"
    args:
      - "-eEuo"
      - "pipefail"
      - "-c"
      - |-
        pip install -r src/main/docker/requirements.txt
        if [[ "${BRANCH_NAME}" != "main" ]]; then
          SUFFIX=".${BUILD_ID}"
        fi
        make REGISTRY=${_REGISTRY} IMAGE_SUFFIX=$${SUFFIX}  push

logsBucket: "gs://cloud-build-dev.starr-data.us"
